version: '3.9'
services:
  api:
    container_name: nest_api
    build: .
    command: npm run start
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/api
    environment:
      DB_HOST: database
      DB_PORT: 5432

  database:
    image: postgres:13
    restart: always
    container_name: nest_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PSW}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
